vim.keymap.del("n", "gra")
vim.keymap.del("n", "gri")
vim.keymap.del("n", "grn")
vim.keymap.del("n", "grr")
vim.keymap.del("n", "grt")

vim.keymap.set({ "n", "x" }, "s", "<nop>")
vim.keymap.set("n", "<c-d>", "<c-d>zz", { desc = "Half page down" })
vim.keymap.set("n", "<c-u>", "<c-u>zz", { desc = "Half page up" })
vim.keymap.set("n", "j", [[v:count == 0 ? 'gj' : 'j']], { expr = true, silent = true, desc = "Down (wrap-aware)" })
vim.keymap.set("n", "k", [[v:count == 0 ? 'gk' : 'k']], { expr = true, silent = true, desc = "Up (wrap-aware)" })
vim.keymap.set("n", "N", "'nN'[v:searchforward].'zv'", { expr = true, silent = true, desc = "Previous search result" })
vim.keymap.set("o", "N", "'nN'[v:searchforward]", { expr = true, silent = true, desc = "Previous search result" })
vim.keymap.set("x", "N", "'nN'[v:searchforward]", { expr = true, silent = true, desc = "Previous search result" })
vim.keymap.set("n", "n", "'Nn'[v:searchforward].'zv'", { expr = true, silent = true, desc = "Next search result" })
vim.keymap.set("o", "n", "'Nn'[v:searchforward]", { expr = true, silent = true, desc = "Next search result" })
vim.keymap.set("x", "n", "'Nn'[v:searchforward]", { expr = true, silent = true, desc = "Next search result" })
vim.keymap.set("t", "<esc><esc>", "<c-\\><c-n>", { silent = true, desc = "Exit terminal mode" })
vim.keymap.set("n", "[<tab>", "<cmd>tabprevious<cr>", { desc = "Previous" })
vim.keymap.set("n", "]<tab>", "<cmd>tabnext<cr>", { desc = "Next" })
vim.keymap.set("n", "<leader>-", "<cmd>split<cr>", { desc = "Split (H)" })
vim.keymap.set("n", "<leader><leader>", "<c-^>", { desc = "Alternate file" })
vim.keymap.set("n", "<leader><tab>G", "<cmd>tablast<cr>", { desc = "Last" })
vim.keymap.set("n", "<leader><tab>e", "<cmd>tabedit %<cr>", { desc = "Edit" })
vim.keymap.set("n", "<leader><tab>g", "<cmd>tabfirst<cr>", { desc = "First" })
vim.keymap.set("n", "<leader><tab>k", "<cmd>tabonly<cr>", { desc = "Keep" })
vim.keymap.set("n", "<leader><tab>n", "<cmd>tabnew<cr>", { desc = "New" })
vim.keymap.set("n", "<leader><tab>q", "<cmd>tabclose<cr>", { desc = "Close" })
vim.keymap.set("n", "<leader>\\", "<cmd>vsplit<cr>", { desc = "Split (V)" })
vim.keymap.set("n", "<leader>bG", "<cmd>blast<cr>", { desc = "Last" })
vim.keymap.set("n", "<leader>bg", "<cmd>bfirst<cr>", { desc = "First" })
vim.keymap.set("n", "<leader>bk", "<cmd>wall!<bar>%bdelete<bar>edit#<bar>bdelete#<cr>", { desc = "Keep this" })
vim.keymap.set("n", "<leader>u", "<cmd>UndotreeToggle<cr>", { desc = "Undo Tree" })
vim.keymap.set("n", "<leader>w", "<cmd>silent w!<cr>", { desc = "Write" })

vim.keymap.set("n", "<leader>T", function()
  vim.ui.input({ prompt = "Name: " }, function(name)
    if name then vim.cmd("terminal zsh \\# " .. name) end
  end)
end, { desc = "Open new terminal" })

vim.keymap.set("n", "<leader>q", function()
  if vim.list_contains(vim.v.argv, "--embed") then
    vim.cmd.quit()
    return
  end

  vim.cmd.detach()
end, { desc = "Quit" })
