safely("now", function()
  local splits = require("smart-splits")

  splits.setup({ cursor_follows_swapped_bufs = true })

  vim.keymap.set({ "n", "t" }, "<a-h>", splits.resize_left)
  vim.keymap.set({ "n", "t" }, "<a-j>", splits.resize_down)
  vim.keymap.set({ "n", "t" }, "<a-k>", splits.resize_up)
  vim.keymap.set({ "n", "t" }, "<a-l>", splits.resize_right)
  vim.keymap.set({ "n", "t" }, "<c-h>", splits.move_cursor_left)
  vim.keymap.set({ "n", "t" }, "<c-j>", splits.move_cursor_down)
  vim.keymap.set({ "n", "t" }, "<c-k>", splits.move_cursor_up)
  vim.keymap.set({ "n", "t" }, "<c-l>", splits.move_cursor_right)
  vim.keymap.set("n", "<c-left>", splits.swap_buf_left)
  vim.keymap.set("n", "<c-down>", splits.swap_buf_down)
  vim.keymap.set("n", "<c-up>", splits.swap_buf_up)
  vim.keymap.set("n", "<c-right>", splits.swap_buf_right)
end)
