local bufnr = vim.api.nvim_get_current_buf()

vim.keymap.set("n", "<leader>ts", "", { buffer = bufnr, desc = "+sort" })
vim.keymap.set("n", "<cr>", "<Plug>(TodoTxtToggleState)", { buffer = bufnr, desc = "Toggle task state" })
vim.keymap.set("n", "<c-c>n", "<Plug>(TodoTxtCyclePriority)", { buffer = bufnr, desc = "Cycle priority" })
vim.keymap.set("n", "<leader>tm", "<Plug>(TodoTxtMoveDone)", { buffer = bufnr, desc = "Move done tasks" })
vim.keymap.set("n", "<leader>tss", "<Plug>(TodoTxtSortTasks)", { buffer = bufnr, desc = "Sort tasks (default)" })
vim.keymap.set("n", "<leader>tsp", "<Plug>(TodoTxtSortByPriority)", { buffer = bufnr, desc = "Sort by priority" })
vim.keymap.set("n", "<leader>tsc", "<Plug>(TodoTxtSortByContext)", { buffer = bufnr, desc = "Sort by context" })
vim.keymap.set("n", "<leader>tsP", "<Plug>(TodoTxtSortByProject)", { buffer = bufnr, desc = "Sort by project" })
vim.keymap.set("n", "<leader>tsd", "<Plug>(TodoTxtSortByDueDate)", { buffer = bufnr, desc = "Sort by due date" })
