safely("event:BufReadPost", function()
  require("mini.trailspace").setup()
  vim.api.nvim_create_user_command("Trim", function()
    MiniTrailspace.trim()
    MiniTrailspace.trim_last_lines()
    vim.cmd.write()
  end, { desc = "Trim trailing whitespace and last empty lines" })
end)
