{
  config,
  lib,
  pkgs,
  ...
}: {
  options.packages.enable = lib.mkEnableOption "enable packages";

  config = lib.mkIf config.packages.enable {
    home.packages = with pkgs; let
      gcloud = google-cloud-sdk.withExtraComponents (with google-cloud-sdk.components; [
        gke-gcloud-auth-plugin
      ]);
    in [
      ansible
      bitwarden
      bitwarden-cli
      brave
      brightnessctl
      deluge
      deno
      docker-credential-helpers
      droidcam
      elixir
      exiftool
      fd
      ffmpeg
      ffmpegthumbnailer
      gcloud
      gdu
      gnumake
      gnused
      gparted
      graphviz
      grim
      hugo
      hyprland-qtutils
      imagemagick
      inkscape
      jdk
      jq
      just
      kooha
      kubectl
      kubernetes-helm
      lazydocker
      libreoffice
      lynx
      minikube
      mongosh
      networkmanagerapplet
      nix-prefetch-github
      parallel
      pasystray
      pavucontrol
      phockup
      playerctl
      plex
      poppler
      postgresql
      protonvpn-gui
      python313
      qalculate-gtk
      quarto
      qview
      satty
      slurp
      sshfs
      sshs
      stremio
      tectonic
      terraform
      uv
      ventoy
      vesktop
      vlc
      wofi-emoji
      zotero
    ];
  };
}
