{
  programs.plasma = {
    enable = true;
    shortcuts = {
      "ksmserver" = {
        "Lock Session" = "Meta+Esc";
        "Log Out" = "Ctrl+Alt+Del";
      };
      "kwin" = {
        "Kill Window" = "Meta+Shift+Q,none,Kill Window";
        "KrohnkiteFloatAll" = "Meta+Shift+F,none,Krohnkite: Float All";
        "KrohnkiteFocusDown" = "Meta+J,none,Krohnkite: Focus Down";
        "KrohnkiteFocusLeft" = "Meta+H,none,Krohnkite: Focus Left";
        "KrohnkiteFocusRight" = "Meta+L,none,Krohnkite: Focus Right";
        "KrohnkiteFocusUp" = "Meta+K,none,Krohnkite: Focus Up";
        "KrohnkiteGrowHeight" = "Meta++,none,Krohnkite: Grow Height";
        "KrohnkiteGrowWidth" = "Meta+=,none,Krohnkite: Grow Width";
        "KrohnkiteNextLayout" = "Meta+],none,Krohnkite: Next Layout";
        "KrohnkitePreviousLayout" = "Meta+[,none,Krohnkite: Previous Layout";
        "KrohnkiteRotate" = "Meta+R,none,Krohnkite: Rotate";
        "KrohnkiteSetMaster" = "Meta+M,none,Krohnkite: Set master";
        "KrohnkiteShiftDown" = "Meta+Shift+J,none,Krohnkite: Move Down/Next";
        "KrohnkiteShiftLeft" = "Meta+Shift+H,none,Krohnkite: Move Left";
        "KrohnkiteShiftRight" = "Meta+Shift+L,none,Krohnkite: Move Right";
        "KrohnkiteShiftUp" = "Meta+Shift+K,none,Krohnkite: Move Up/Prev";
        "KrohnkiteShrinkHeight" = "Meta+_,none,Krohnkite: Shrink Height";
        "KrohnkiteShrinkWidth" = "Meta+-,none,Krohnkite: Shrink Width";
        "KrohnkiteToggleFloat" = "Meta+F,none,Krohnkite: Toggle Float";
        "KrohnkiteDecrease" = "Meta+D,none,Krohnkite: Decrease";
        "KrohnkiteIncrease" = "Meta+I,none,Krohnkite: Increase";
        "Overview" = "Meta+W";
        "Switch to Desktop 1" = "Meta+1,,Switch to Desktop 1";
        "Switch to Desktop 2" = "Meta+2,,Switch to Desktop 2";
        "Switch to Desktop 3" = "Meta+3,,Switch to Desktop 3";
        "Switch to Desktop 4" = "Meta+4,,Switch to Desktop 4";
        "Switch to Desktop 5" = "Meta+5,,Switch to Desktop 5";
        "Switch to Desktop 6" = "Meta+6,,Switch to Desktop 6";
        "Switch to Desktop 7" = "Meta+7,,Switch to Desktop 7";
        "Switch to Desktop 8" = "Meta+8,,Switch to Desktop 8";
        "Switch to Desktop 9" = "Meta+9,,Switch to Desktop 9";
        "Switch to Next Desktop" = "Meta+Ctrl+L,,Switch to Next Desktop";
        "Switch to Next Screen" = "Meta+N,,Switch to Next Screen";
        "Switch to Previous Desktop" = "Meta+Ctrl+H,,Switch to Previous Desktop";
        "Switch to Previous Screen" = "Meta+P,,Switch to Previous Screen";
        "Switch to Screen 0" = "Meta+F1,,Switch to Screen 0";
        "Switch to Screen 1" = "Meta+F2,,Switch to Screen 1";
        "Walk Through Windows (Reverse)" = "Meta+Shift+Tab,,Walk Through Windows (Reverse)";
        "Walk Through Windows" = "Meta+Tab,,Walk Through Windows";
        "Window Close" = "Meta+Q,Alt+F4,Close Window";
        "Window Fullscreen" = "Meta+Z,,Make Window Fullscreen";
        "Window One Desktop Down" = "Meta+Ctrl+Shift+J,,Window One Desktop Down";
        "Window One Desktop Up" = "Meta+Ctrl+Shift+K,,Window One Desktop Up";
        "Window One Desktop to the Left" = "Meta+Ctrl+Shift+H,,Window One Desktop to the Left";
        "Window One Desktop to the Right" = "Meta+Ctrl+Shift+L,,Window One Desktop to the Right";
        "Window to Desktop 1" = "Meta+!,,Window to Desktop 1";
        "Window to Desktop 2" = "Meta+@,,Window to Desktop 2";
        "Window to Desktop 3" = "Meta+#,,Window to Desktop 3";
        "Window to Desktop 4" = "Meta+$,,Window to Desktop 4";
        "Window to Desktop 5" = "Meta+%,,Window to Desktop 5";
        "Window to Desktop 6" = "Meta+^,,Window to Desktop 6";
        "Window to Desktop 7" = "Meta+&,,Window to Desktop 7";
        "Window to Desktop 8" = "Meta+*,,Window to Desktop 8";
        "Window to Desktop 9" = "Meta+(,,Window to Desktop 9";
        "Window to Next Screen" = "Meta+Shift+N,Meta+Shift+Right,Move Window to Next Screen";
        "Window to Previous Screen" = "Meta+Shift+P,Meta+Shift+Left,Move Window to Previous Screen";
        "Window to Screen 0" = "Meta+Shift+F1,,Move Window to Screen 0";
        "Window to Screen 1" = "Meta+Shift+F2,,Move Window to Screen 1";
      };
      "plasmashell" = {
        "activate application launcher" = "none,Meta,Activate Application Launcher";
        "activate task manager entry 1" = "none,Meta+1,Activate Task Manager Entry 1";
        "activate task manager entry 2" = "none,Meta+2,Activate Task Manager Entry 2";
        "activate task manager entry 3" = "none,Meta+3,Activate Task Manager Entry 3";
        "activate task manager entry 4" = "none,Meta+4,Activate Task Manager Entry 4";
        "activate task manager entry 5" = "none,Meta+5,Activate Task Manager Entry 5";
        "activate task manager entry 6" = "none,Meta+6,Activate Task Manager Entry 6";
        "activate task manager entry 7" = "none,Meta+7,Activate Task Manager Entry 7";
        "activate task manager entry 8" = "none,Meta+8,Activate Task Manager Entry 8";
        "activate task manager entry 9" = "none,Meta+9,Activate Task Manager Entry 9";
        "show-on-mouse-pos" = "Meta+V";
      };
      "services/kitty.desktop"."_launch" = "Meta+Return";
      "services/org.kde.plasma.emojier.desktop"."_launch" = "Meta+/";
      "services/org.kde.spectacle.desktop"."RectangularRegionScreenShot" = "Print";
    };
    configFile = {
      "kwinrc" = {
        "Tiling"."padding" = 4;
        "Windows"."SeparateScreenFocus" = true;
        "NightColor"."Active" = true;
        "Script-desktopchangeosd"."TextOnly" = true;
        "Xwayland"."Scale" = 1;
        "Desktops" = {
          "Id_1" = "30d1a592-2e0c-4f1a-8521-655fd600b79d";
          "Id_2" = "1daea2f3-3eae-4a07-93e3-0ff3b19be29a";
          "Id_3" = "730cc12c-05f8-437f-a289-3e35aa8f0b86";
          "Id_4" = "78a8a8b0-d15d-4eac-b478-444b49d01696";
          "Id_5" = "4aafa068-61b9-440d-809b-0aae271a89d4";
          "Id_6" = "41454db8-afc2-47eb-b1b6-3505caf7c18c";
          "Id_7" = "c3747e65-5211-4085-bd38-889c93acdc92";
          "Id_8" = "3402c341-84cc-4b0c-b119-ae68cac5c1d7";
          "Id_9" = "5e7c1574-ffae-4b4b-b5f8-d6154a088698";
          "Name_1" = 1;
          "Name_2" = 2;
          "Name_3" = 3;
          "Name_4" = 4;
          "Name_5" = 5;
          "Name_6" = 6;
          "Name_7" = 7;
          "Name_8" = 8;
          "Name_9" = 9;
          "Number" = 9;
          "Rows" = 1;
        };
        "Plugins" = {
          "desktopchangeosdEnabled" = true;
          "krohnkiteEnabled" = true;
        };
        "Script-krohnkite" = {
          "enableBTreeLayout" = true;
          "enableQuarterLayout" = true;
          "enableStackedLayout" = true;
          "ignoreClass" = "krunner,yakuake,spectacle,kded5,xwaylandvideobridge,plasmashell,ksplashqml,emojier";
          "keepFloatAbove" = false;
          "screenGapBottom" = 5;
          "screenGapLeft" = 5;
          "screenGapRight" = 5;
          "screenGapTop" = 5;
          "tileLayoutGap" = 5;
        };
      };
      "plasma-localerc" = {
        "Formats"."LANG" = "en_US.UTF-8";
        "Formats"."LC_MEASUREMENT" = "pt_BR.UTF-8";
        "Formats"."LC_MONETARY" = "pt_BR.UTF-8";
        "Formats"."LC_NUMERIC" = "pt_BR.UTF-8";
        "Formats"."LC_PAPER" = "pt_BR.UTF-8";
        "Formats"."LC_TIME" = "pt_BR.UTF-8";
      };
    };
  };
}
