local bufremove = require("mini.bufremove")
local hicursorword = require("mini.cursorword")
local indentscope = require("mini.indentscope")
local pairs = require("mini.pairs")
local starter = require("mini.starter")
local statusline = require("mini.statusline")
local tabline = require("mini.tabline")

bufremove.setup()
hicursorword.setup()
indentscope.setup()
pairs.setup()
starter.setup()
tabline.setup()
statusline.setup({ set_vim_settings = false })
