local bufremove = require("mini.bufremove")
local indentscope = require("mini.indentscope")
local pairs = require("mini.pairs")
local starter = require("mini.starter")
local tabline = require("mini.tabline")

bufremove.setup()
indentscope.setup()
pairs.setup()
starter.setup()
tabline.setup()
