repos:
  - repo: local
    hooks:
      - id: nixfmt
        name: nixfmt
        entry: nix run nixpkgs#nixfmt --
        language: system
        files: \.nix$

      - id: deadnix
        name: deadnix
        entry: nix run nixpkgs#deadnix --
        language: system
        files: \.nix$

      - id: statix
        name: statix
        entry: nix run nixpkgs#statix -- check -i '**/.devenv/**'
        language: system
        files: \.nix$
        pass_filenames: false

      - id: stylua
        name: stylua
        entry: nix run nixpkgs#stylua --
        language: system
        files: \.lua$

      - id: luacheck
        name: luacheck
        entry: nix run nixpkgs#luaPackages.luacheck -- --config .luacheckrc
        language: system
        files: \.lua$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: "^secrets/"
      - id: end-of-file-fixer
        exclude: "^secrets/"
      - id: mixed-line-ending
        exclude: "^secrets/"
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
        exclude: "^secrets/"
      - id: check-toml

  - repo: local
    hooks:
      - id: flake-check
        name: nix-flake-check
        entry: nix flake check
        language: system
        pass_filenames: false
        stages: [pre-push]
