---
- name: Deploy changes in server
  hosts: server
  vars:
    ansible_user: phrmendes
    ansible_become_user: root

  tasks:
    - name: Pull latest changes in dotfiles
      ansible.builtin.git:
        repo: https://github.com/phrmendes/dotfiles.git
        dest: "/home/{{ ansible_user }}/dotfiles"
        update: true
      register: git_result

    - name: Rebuild NixOS configuration
      become: true
      ansible.builtin.command:
        cmd: nixos-rebuild switch --flake .#server
        chdir: "/home/{{ ansible_user }}/dotfiles"
      when: git_result.after != git_result.before
