{pkgs, ...}: {
  home.packages =
    (with pkgs; [
      ansible
      bashly
      bitwarden
      bruno
      chromium
      curtail
      dbeaver
      deluge
      droidcam
      evince
      firefox
      fselect
      gcolor3
      gh
      git
      gparted
      graphviz
      grex
      httpie
      hugo
      jq
      just
      kubectl
      kubernetes-helm
      libreoffice
      mc
      minikube
      nautilus-open-any-terminal
      ncdu
      obsidian
      opentofu
      pandoc
      parallel
      peek
      phockup
      pop-launcher
      qalculate-gtk
      qemu
      quarto
      quickemu
      qview
      syncthingtray
      tectonic
      terraform
      tokei
      ventoy
      vlc
      zotero
    ])
    ++ (with pkgs.gnome; [
      file-roller
      gnome-tweaks
      nautilus
    ])
    ++ (with pkgs.gnomeExtensions; [
      appindicator
      espresso
      pop-shell
      user-themes
    ]);
}
