{
  programs = {
    sioyek = {
      enable = true;
      bindings = {
        "add_bookmark" = "ab";
        "add_highlight" = "ah";
        "portal" = "ap";
        "fit_to_page_width" = "F";
        "fit_to_page_width_smart" = "f";
        "goto_begining" = "gg";
        "goto_bookmark" = "gb";
        "goto_definition" = "gd";
        "goto_end" = "G";
        "goto_highlight" = "gh";
        "goto_mark" = "gm";
        "goto_toc" = "gt";
        "move_down" = "j";
        "move_left" = "h";
        "move_right" = "l";
        "move_up" = "k";
        "next_item" = "n";
        "next_page" = "<C-j>";
        "open_document" = "o";
        "overview_definition" = "K";
        "portal_to_definition" = "P";
        "previous_item" = "p";
        "previous_page" = "<C-k>";
        "search" = "/";
        "set_mark" = "m";
        "zoom_in" = "=";
        "zoom_out" = "-";
        "screen_down" = "<C-d>";
        "screen_up" = "<C-u>";
        "delete_highlight" = "dh";
        "delete_bookmark" = "db";
        "delete_portal" = "dp";
        "edit_portal" = "ep";
        "open_prev_doc" = "O";
        "copy" = "y";
        "toggle_fullscreen" = "z";
        "toggle_highlight" = "t";
        "toggle_dark_mode" = "T";
      };
      config = {
        "startup_commands" = "toggle_titlebar";
        "background_color" = "#1e1e2e";
        "custom_background_color" = "#1e1e2e";
        "custom_text_color" = "#cdd6f4";
        "highlight_color_a" = "#f9e2af";
        "highlight_color_b" = "#a6e3a1";
        "highlight_color_c" = "#89dceb";
        "highlight_color_d" = "#eba0ac";
        "highlight_color_e" = "#cba6f7";
        "highlight_color_f" = "#f38ba8";
        "highlight_color_g" = "#f9e2af";
        "link_highlight_color" = "#89b4fa";
        "search_highlight_color " = "#f9e2af";
        "synctex_highlight_color" = "#a6e3a1";
        "text_highlight_colo" = "#f9e2af";
        "ui_background_color" = "#313244";
        "ui_font" = "FiraCode Nerd Font";
        "ui_selected_background_color" = "#585b70";
        "ui_selected_text_color" = "#cdd6f4";
        "ui_text_color" = "#cdd6f4";
        "visual_mark_color" = "#7f849c";
      };
    };
  };
}
