{
  config,
  lib,
  pkgs,
  ...
}:
{
  options.packages.enable = lib.mkEnableOption "enable packages";

  config = lib.mkIf config.packages.enable {
    home.packages = with pkgs; [
      curl
      deluge-gtk
      drawing
      elixir
      exiftool
      ffmpeg
      ffmpegthumbnailer
      file-roller
      filezilla
      firefox
      gcolor3
      gdu
      grim
      imagemagick
      jdk
      jqp
      just
      kubectl
      kubernetes-helm
      libqalculate
      networkmanagerapplet
      nix-prefetch-github
      nodejs_latest
      obs-studio
      onlyoffice-desktopeditors
      parallel
      pass
      pasystray
      pavucontrol
      phockup
      poppler
      proton-vpn
      python314
      quarto
      tectonic
      terraform
      thunar
      tpm2-tools
      ungoogled-chromium
      uv
      vesktop
      zotero
    ];
  };
}
