require("plugins.mini.ai")
require("plugins.mini.bracketed")
require("plugins.mini.bufremove")
require("plugins.mini.comment")
require("plugins.mini.jumping")
require("plugins.mini.move")
require("plugins.mini.splitjoin")
require("plugins.mini.surround")

require("mini.align").setup()
require("mini.cursorword").setup()
require("mini.fuzzy").setup()
require("mini.operators").setup()
require("mini.pairs").setup()
require("mini.starter").setup()
require("mini.tabline").setup()
require("mini.trailspace").setup()
