services:
  atuin:
    image: ghcr.io/atuinsh/atuin:latest
    container_name: atuin
    restart: unless-stopped
    command: server start
    volumes:
      - atuin_config:/config
    environment:
      - ATUIN_HOST=0.0.0.0
      - ATUIN_OPEN_REGISTRATION=true
      - ATUIN_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/atuin
      - RUST_LOG=info,atuin_server=debug
    networks:
      - caddy
      - default
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - diun.enable=true

volumes:
  atuin_config:
