services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - bazarr_config:/config
      - /mnt/external/tvshows:/tv
      - /mnt/external/downloads:/downloads
      - /mnt/external/movies:/movies
    networks:
      - caddy
      - default

volumes:
  bazarr_config:
