services:
  beszel-agent:
    image: docker.io/henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: always
    network_mode: host
    volumes:
      - beszel_agent_data:/var/lib/beszel-agent
      - beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HUB_URL=http://beszel:8090
      - KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIIR9/sS1/jqtENlx6ljeHtwJm8xI2Z3vMtQpTl0YThS
      - LISTEN=/beszel_socket/beszel.sock
      - TOKEN=${BESZEL_TOKEN}
    healthcheck:
      test: ["CMD", "/agent", "health"]
      interval: 120s
    labels:
      - diun.enable=true

  beszel:
    image: docker.io/henrygd/beszel:latest
    container_name: beszel
    restart: always
    ports:
      - 8090:8090
    volumes:
      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      start_period: 5s
      interval: 120s
    labels:
      - diun.enable=true

volumes:
  beszel_data:
  beszel_agent_data:
  beszel_socket:
