services:
  dozzle:
    image: docker.io/amir20/dozzle:latest
    container_name: dozzle
    restart: always
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
      - DOZZLE_REMOTE_HOST=tcp://socket-proxy:2375
    labels:
      - diun.enable=true
    depends_on:
      - socket-proxy
