services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - GOTIFY_URL=${GOTIFY_URL}
      - CLI_ARGS="--run-script-after = duplicati-gotify-notification.sh"
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_WEBSERVICE_PASSWORD}
      - GOTIFY_DUPLICATI_TOKEN=${GOTIFY_DUPLICATI_TOKEN}
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_ENCRYPTION_KEY}
    volumes:
      - duplicati_backups:/backups
      - duplicati_config:/config
      - duplicati_source:/source
      - linkding_data:/backups/linkding
      - postgres_dumps:/backups/postgres_dumps
      - syncthing_data:/backups/syncthing
      - ./files/duplicati-gotify-notification.sh:/app/duplicati/duplicati-gotify-notification.sh
    ports:
      - 8200:8200
    labels:
      - diun.enable=true

volumes:
  duplicati_backups:
  duplicati_config:
  duplicati_source:
