services:
  duplicati:
    image: docker.io/linuxserver/duplicati:latest
    container_name: duplicati
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - CLI_ARGS=--run-script-after = gotify.sh
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_WEBSERVICE_PASSWORD}
      - GOTIFY_URL=${GOTIFY_URL}
      - GOTIFY_DUPLICATI_TOKEN=${GOTIFY_DUPLICATI_TOKEN}
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_ENCRYPTION_KEY}
    volumes:
      - duplicati_backups:/backups
      - duplicati_config:/config
      - duplicati_source:/source
      - linkding_data:/backups/linkding
      - postgres_dumps:/backups/postgres_dumps
      - syncthing_data:/backups/syncthing
      - ./files/gotify/duplicati.sh:/app/duplicati/gotify.sh
    labels:
      - diun.enable=true
    networks:
      - caddy

volumes:
  duplicati_backups:
  duplicati_config:
  duplicati_source:
