services:
  excalidraw:
    image: docker.io/excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: always
    ports:
      - 5000:80
    labels:
      - diun.enable=true
      - homepage.group=Notes
      - homepage.name=Excalidraw
      - homepage.href=https://excalidraw.ts.ohlongjohnson.tech
