services:
  gotify:
    image: docker.io/gotify/server:latest
    container_name: gotify
    restart: unless-stopped
    volumes:
      - gotify_data:/app/data
    environment:
      - GOTIFY_DEFAULTUSER_NAME=phrmendes
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - diun.enable=true

volumes:
  gotify_data:
