services:
  jellyfin:
    image: docker.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - jellyfin_data:/config
      - /mnt/external/movies:/data/movies
      - /mnt/external/tvshows:/data/tvshows
    ports:
      - 7359:7359/udp
    networks:
      - caddy
      - default
    labels:
      - diun.enable=true

volumes:
  jellyfin_data:
