services:
  jellyfin:
    image: docker.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - jellyfin_data:/config
      - /mnt/external/movies:/data/movies
      - /mnt/external/tvshows:/data/tvshows
    ports:
      - 7359:7359/udp
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:8096/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - diun.enable=true

volumes:
  jellyfin_data:
