services:
  linkding:
    image: docker.io/sissbruecker/linkding:latest-plus
    container_name: linkding
    restart: always
    environment:
      - LD_DB_DATABASE=linkding
      - LD_DB_ENGINE=postgres
      - LD_DB_HOST=postgres
      - LD_DB_PORT=5432
      - LD_DB_USER=${POSTGRES_USER}
      - LD_DB_PASSWORD=${POSTGRES_PASSWORD}
      - LD_SUPERUSER_NAME=${LD_SUPERUSER_NAME}
      - LD_SUPERUSER_PASSWORD=${LD_SUPERUSER_PASSWORD}
    volumes:
      - linkding_data:/etc/linkding/data
    ports:
      - 9090:9090
    depends_on:
      - postgres
    labels:
      - diun.enable=true
      - homepage.group=Bookmarks
      - homepage.name=Linkding
      - homepage.href=https://linkding.ts.ohlongjohnson.tech

volumes:
  linkding_data:
