services:
  postgres:
    image: docker.io/postgres:17
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./files/postgres_init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASES=${POSTGRES_DATABASES}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - diun.enable=true

  pgbackup:
    image: docker.io/prodrigestivill/postgres-backup-local:latest
    container_name: pgbackup
    restart: always
    volumes:
      - postgres_dumps:/dumps
    environment:
      - TZ=${TZ}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DATABASES}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_ON_START=TRUE
      - BACKUP_DIR=/dumps
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - diun.enable=true

volumes:
  postgres_data:
  postgres_dumps:
