services:
  prowlarr:
    image: docker.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - prowlarr_config:/config
    networks:
      - caddy
      - default
    labels:
      - diun.enable=true

volumes:
  prowlarr_config:
