services:
  prunemate:
    image: anoniemerd/prunemate:latest
    container_name: prunemate
    restart: unless-stopped
    volumes:
      - prunemate_logs:/var/log
    secrets:
      - source: prunemate
        target: /config/config.json
    environment:
      - PRUNEMATE_TZ=${TZ}
      - PRUNEMATE_TIME_24H=true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python3 -c "import socket; s=socket.socket(); s.settimeout(3); s.connect((''127.0.0.1'',8080)); s.close()" || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - diun.enable=true

volumes:
  prunemate_logs:

secrets:
  prunemate:
    file: ${AGE_SECRETS_PATH}/prunemate.json
