services:
  radarr:
    image: docker.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - radarr_config:/config
      - /mnt/external/movies:/movies
      - /mnt/external/downloads:/downloads
    networks:
      - caddy
      - default
    labels:
      - diun.enable=true

volumes:
  radarr_config:
