services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - radarr_config:/config
      - /mnt/external/movies:/movies
      - /mnt/external/downloads:/downloads

volumes:
  radarr_config:
