services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    volumes:
      - searxng_data:/var/cache/searxng
    environment:
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
      - SEARXNG_BASE_URL=https://searxng.local.ohlongjohnson.tech
    networks:
      - caddy
      - default

  redis:
    image: docker.io/valkey/valkey:8-alpine
    container_name: redis
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  searxng_data:
