services:
  sftpgo:
    image: docker.io/drakkan/sftpgo:latest
    container_name: sftpgo
    restart: always
    volumes:
      - sftpgo_data:/var/lib/sftpgo
      - postgres_dumps:/files/dumps
      - syncthing_data:/files/syncthing
      - transmission_watch:/files/watch
      - /mnt/external/:/files/external
    ports:
      - 8081:8080
      - 2022:2022
    labels:
      - diun.enable=true

volumes:
  sftpgo_data:
