services:
  sftpgo:
    image: docker.io/drakkan/sftpgo:latest
    container_name: sftpgo
    restart: unless-stopped
    volumes:
      - /mnt/external/:/files/external
      - sftpgo_data:/var/lib/sftpgo
      - postgres_dumps:/files/dumps
      - syncthing_data:/files/syncthing
      - transmission_watch:/files/watch
    environment:
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080
    ports:
      - 2022:2022
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/8080' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - diun.enable=true

volumes:
  sftpgo_data:
