services:
  sonarr:
    image: docker.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - sonarr_config:/config
      - /mnt/external/tvshows:/tv
      - /mnt/external/downloads:/downloads
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:8989/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - diun.enable=true

volumes:
  sonarr_config:
