services:
  sonarr:
    image: docker.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - sonarr_config:/config
      - /mnt/external/tvshows:/tv
      - /mnt/external/downloads:/downloads
    networks:
      - caddy
      - default
    labels:
      - diun.enable=true

volumes:
  sonarr_config:
