services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - syncthing_config:/config
      - syncthing_data:/data
    ports:
      - 21027:21027/udp
      - 22000:22000
      - 22000:22000/udp
      - 8384:8384
    labels:
      - diun.enable=true
      - homepage.group=File management
      - homepage.name=Syncthing
      - homepage.href=https://syncthing.ts.ohlongjohnson.tech

volumes:
  syncthing_config:
  syncthing_data:
