services:
  syncthing:
    image: docker.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - syncthing_config:/config
      - syncthing_data:/data
    ports:
      - 21027:21027/udp
      - 22000:22000
      - 22000:22000/udp
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsSL http://localhost:8384/rest/noauth/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - diun.enable=true

volumes:
  syncthing_config:
  syncthing_data:
