services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - GOTIFY_URL=${GOTIFY_URL}
      - GOTIFY_TRANSMISSION_TOKEN=${GOTIFY_TRANSMISSION_TOKEN}
    volumes:
      - transmission_config:/config
      - transmission_watch:/watch
      - /mnt/external/downloads:/downloads
      - ./files/gotify/transmission.sh:/scripts/gotify.sh
      - /run/agenix/transmission.json:/config/settings.json
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    labels:
      - diun.enable=true
      - homepage.group=Files
      - homepage.name=Transmission
      - homepage.href=https://transmission.ts.ohlongjohnson.tech

volumes:
  transmission_config:
  transmission_watch:
