services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - USER=phrmendes
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - transmission_config:/config
      - transmission_watch:/watch
      - /mnt/external/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    labels:
      - diun.enable=true

volumes:
  transmission_config:
  transmission_watch:
