{pkgs, ...}: {
  home.packages =
    (with pkgs; [
      ansible
      bashly
      beekeeper-studio
      bitwarden
      bruno
      celluloid
      chromium
      csvkit
      deja-dup
      docker-compose
      droidcam
      eza
      firefox
      fragments
      gcolor3
      gh
      git
      gnome-extensions-cli
      gthumb
      hugo
      imagemagick
      jdk21
      just
      kubectl
      kubernetes-helm
      lazydocker
      libreoffice
      minikube
      ncdu
      neovide
      nodejs_21
      obsidian
      parallel
      pop-launcher
      python312
      quarto
      spot
      syncthingtray
      tealdeer
      tectonic
      terraform
      ueberzugpp
      ventoy
      wezterm
      zotero
    ])
    ++ (with pkgs.gnome; [
      file-roller
      gnome-calculator
      gnome-disk-utility
      gnome-tweaks
      nautilus
    ])
    ++ (with pkgs.gnomeExtensions; [
      appindicator
      espresso
      pop-shell
    ]);
}
