require("conform").formatters_by_ft = {
	css = { "prettier" },
	elixir = { "mix" },
	html = { "prettier" },
	json = { "prettier" },
	lua = { "stylua" },
	markdown = { "prettier" },
	nix = { "alejandra" },
	python = { "ruff_fix", "ruff_format", "ruff_organize_imports" },
	scss = { "prettier" },
	sh = { "shellharden" },
	sql = { "sqlfluff" },
	terraform = { "terraform_fmt" },
	toml = { "taplo" },
	yaml = { "prettier" },
}
