local now, later = require("mini.deps").now, require("mini.deps").later

now(function()
	require("plugins.completion")
	require("plugins.lsp")
	require("plugins.mini")
end)

later(function()
	require("plugins.actions-preview")
	require("plugins.autotag")
	require("plugins.colorizer")
	require("plugins.dap")
	require("plugins.dial")
	require("plugins.dressing")
	require("plugins.image")
	require("plugins.jupytext")
	require("plugins.quarto")
	require("plugins.snippets")
	require("plugins.sniprun")
	require("plugins.toggleterm")
	require("plugins.treesitter")
	require("plugins.zen")
end)
