MiniDeps.now(function()
	MiniDeps.add({ source = "mrjones2014/smart-splits.nvim" })

	local smart_splits = require("smart-splits")

	smart_splits.setup({ cursor_follows_swapped_bufs = true })

	vim.keymap.set({ "n", "t" }, "<a-h>", function() smart_splits.resize_left() end)
	vim.keymap.set({ "n", "t" }, "<a-j>", function() smart_splits.resize_down() end)
	vim.keymap.set({ "n", "t" }, "<a-k>", function() smart_splits.resize_up() end)
	vim.keymap.set({ "n", "t" }, "<a-l>", function() smart_splits.resize_right() end)
	vim.keymap.set({ "n", "t" }, "<c-h>", function() smart_splits.move_cursor_left() end)
	vim.keymap.set({ "n", "t" }, "<c-j>", function() smart_splits.move_cursor_down() end)
	vim.keymap.set({ "n", "t" }, "<c-k>", function() smart_splits.move_cursor_up() end)
	vim.keymap.set({ "n", "t" }, "<c-l>", function() smart_splits.move_cursor_right() end)
	vim.keymap.set("n", "<c-left>", function() smart_splits.swap_buf_left() end)
	vim.keymap.set("n", "<c-down>", function() smart_splits.swap_buf_down() end)
	vim.keymap.set("n", "<c-up>", function() smart_splits.swap_buf_up() end)
	vim.keymap.set("n", "<c-right>", function() smart_splits.swap_buf_right() end)
end)
