return {
	"nvim-treesitter/nvim-treesitter",
	dependencies = {
		"nvim-treesitter/nvim-treesitter-textobjects",
		"nvim-treesitter/nvim-treesitter-context",
	},
	build = ":TSUpdate",
	event = { "VeryLazy" },
	lazy = vim.fn.argc(-1) == 0,
	cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
	opts = {
		ensure_installed = {
			"bash",
			"bibtex",
			"css",
			"csv",
			"cuda",
			"diff",
			"dockerfile",
			"dot",
			"eex",
			"elixir",
			"erlang",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"hcl",
			"heex",
			"helm",
			"html",
			"htmldjango",
			"hyprlang",
			"javascript",
			"json",
			"jsonc",
			"just",
			"latex",
			"lua",
			"luadoc",
			"luap",
			"make",
			"markdown",
			"markdown_inline",
			"mermaid",
			"nginx",
			"nix",
			"python",
			"requirements",
			"sql",
			"ssh_config",
			"terraform",
			"todotxt",
			"toml",
			"typescript",
			"vim",
			"vimdoc",
			"yaml",
		},
		indent = { enable = true },
		textobjects = {
			select = { enable = false },
			move = {
				enable = true,
				goto_next_start = { ["]f"] = "@function.outer", ["]c"] = "@class.outer" },
				goto_next_end = { ["]F"] = "@function.outer", ["]C"] = "@class.outer" },
				goto_previous_start = { ["[f"] = "@function.outer", ["[c"] = "@class.outer" },
				goto_previous_end = { ["[F"] = "@function.outer", ["[C"] = "@class.outer" },
			},
		},
		highlight = { enable = true, additional_vim_regex_highlighting = { "markdown" } },
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<c-s>",
				node_incremental = "<c-s>",
				scope_incremental = false,
				node_decremental = "<c-bs>",
			},
		},
	},
	config = function(_, opts) require("nvim-treesitter.configs").setup(opts) end,
}
