{pkgs, ...}: {
  home.packages =
    (with pkgs; [
      ansible
      appimage-run
      bashly
      beekeeper-studio
      binutils
      bitwarden
      bruno
      caffeine-ng
      chromium
      cmake
      coursier
      curl
      docker-compose
      droidcam
      evince
      eza
      fd
      firefox
      fragments
      gcc
      gh
      git
      gnumake
      gzip
      hugo
      hunspell
      jdk21
      kubectl
      kubernetes-helm
      libreoffice
      micromamba
      minikube
      ncdu
      neovide
      nodejs_21
      obsidian
      parallel
      peek
      podman-compose
      podman-desktop
      podman-tui
      python312
      quarto
      ripgrep
      tealdeer
      terraform
      unrar
      unzip
      vlc
      vscode
      wget
      xclip
      zip
      zlib
      zotero
    ])
    ++ (with pkgs.hunspellDicts; [
      en-us
      pt-br
    ])
    ++ (with pkgs.gnome; [
      file-roller
      gnome-calculator
      gnome-disk-utility
      gnome-screenshot
      gnome-tweaks
      nautilus
    ])
    ++ (with pkgs.gnomeExtensions; [
      appindicator
      forge
      space-bar
      user-themes
    ]);
}
