- Services:
    - Adminer:
        href: https://adminer.local.ohlongjohnson.tech
        icon: sh-adminer
        description: Database administration tool
    - AdGuard Home:
        href: https://adguardhome.local.ohlongjohnson.tech
        icon: sh-adguard-home
        description: DNS sinkhole and network-wide ad blocker
    - Beszel:
        href: https://beszel.local.ohlongjohnson.tech
        icon: sh-beszel
        description: System monitoring dashboard
    - Dozzle:
        href: https://dozzle.local.ohlongjohnson.tech
        icon: sh-dozzle
        description: Docker log viewer
    - Duplicati:
        href: https://duplicati.local.ohlongjohnson.tech
        icon: sh-duplicati
        description: Backup solution for encrypted, remote storage
    - Excalidraw:
        href: https://excalidraw.local.ohlongjohnson.tech
        icon: sh-excalidraw
        description: Virtual whiteboard for sketching diagrams
    - Gotify:
        href: https://gotify.local.ohlongjohnson.tech
        icon: sh-gotify
        description: Self-hosted push notification server
    - Jellyfin:
        href: https://jellyfin.local.ohlongjohnson.tech
        icon: sh-jellyfin
        description: Media streaming server
    - Linkding:
        href: https://linkding.local.ohlongjohnson.tech
        icon: sh-linkding
        description: Bookmark manager with tagging support
    - SFTPGo:
        href: https://sftpgo.local.ohlongjohnson.tech
        icon: sh-sftpgo
        description: SFTP/FTP server with web admin interface
    - Syncthing:
        href: https://syncthing.local.ohlongjohnson.tech
        icon: sh-syncthing
        description: Continuous file synchronization program
    - Transmission:
        href: https://transmission.local.ohlongjohnson.tech
        icon: sh-transmission
        description: BitTorrent client with web interface
    - SABnzbd:
        href: https://sabnzbd.local.ohlongjohnson.tech
        icon: sh-sabnzbd
        description: The automated Usenet download tool
    - Prowlarr:
        href: https://prowlarr.local.ohlongjohnson.tech
        icon: sh-prowlarr
        description: The ultimate indexer manager
    - Sonarr:
        href: https://sonarr.local.ohlongjohnson.tech
        icon: sh-sonarr
        description: TV shows manager for usenet and torrent users
    - Radarr:
        href: https://radarr.local.ohlongjohnson.tech
        icon: sh-radarr
        description: Movie manager for usenet and torrent users
    - Bazarr:
        href: https://bazarr.local.ohlongjohnson.tech
        icon: sh-bazarr
        description: Subtitle manager for *arr stack
    - SearXNG:
        href: https://searxng.local.ohlongjohnson.tech
        icon: sh-searxng
        description: Internet metasearch engine
    - Photoview:
        href: https://photoview.local.ohlongjohnson.tech
        icon: sh-photoview
        description: Gallery management
    - PG Back Web:
        href: https://pgbackweb.local.ohlongjohnson.tech
        icon: sh-pg-back-web
        description: Postgres backup manager
