title: Homelab
theme: dark
color: neutral
base: https://homepage.ts.ohlongjohnson.tech
language: en
disableUpdateCheck: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: duckduckgo
layout:
  Backups:
    style: row
    columns: 2
  Bookmarks:
    style: row
    columns: 2
  Databases:
    style: row
    columns: 2
  Files:
    style: row
    columns: 2
  Media:
    style: row
    columns: 2
  Networking:
    style: row
    columns: 2
  Notes:
    style: row
    columns: 2
  Observability:
    style: row
    columns: 2
