title: Homelab
theme: dark
color: neutral
base: https://homepage.ts.ohlongjohnson.tech
language: en
disableUpdateCheck: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: duckduckgo
layout:
  Bookmarks:
    style: row
    columns: 2
  Services:
    style: row
    columns: 2
