require("plugins.mini.ai")
require("plugins.mini.bufremove")
require("plugins.mini.comment")
require("plugins.mini.indentscope")
require("plugins.mini.jump")
require("plugins.mini.move")
require("plugins.mini.splitjoin")
require("plugins.mini.statusline")
require("plugins.mini.surround")

require("mini.bracketed").setup()
require("mini.cursorword").setup()
require("mini.fuzzy").setup()
require("mini.pairs").setup()
require("mini.starter").setup()
require("mini.tabline").setup()
require("mini.trailspace").setup()
