require("mini.bracketed").setup()
require("mini.cursorword").setup()
require("mini.fuzzy").setup()
require("mini.pairs").setup()
require("mini.starter").setup()
require("mini.tabline").setup()
require("mini.trailspace").setup()
