local bracketed = require("mini.bracketed")
local cursorword = require("mini.cursorword")
local fuzzy = require("mini.fuzzy")
local pairs = require("mini.pairs")
local starter = require("mini.starter")
local tabline = require("mini.tabline")
local trailspace = require("mini.trailspace")

bracketed.setup()
cursorword.setup()
fuzzy.setup()
pairs.setup()
starter.setup()
tabline.setup()
trailspace.setup()
