services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: always
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - jellyfin_data:/config
      - /mnt/external/movies:/data/movies
      - /mnt/external/tvshows:/data/tvshows
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    labels:
      - diun.enable=true

volumes:
  jellyfin_data:
