compose_command := "docker compose --env-file=/run/agenix/docker-compose.env"

default: down up

@down svc="":
    {{compose_command}} down {{svc}}

@up:
    {{compose_command}} up --detach --remove-orphans --force-recreate --pull always

@restart svc="":
    {{compose_command}} down {{svc}}
    {{compose_command}} up --detach --remove-orphans --force-recreate --pull always

@ps:
    {{compose_command}} ps

@clean:
    docker system prune --all
    docker volume prune --all
