services:
  postgres:
    image: docker.io/postgres:17
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASES=atuin,npm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - diun.enable=true

  pgbackup:
    image: docker.io/prodrigestivill/postgres-backup-local:latest
    container_name: pgbackup
    restart: always
    volumes:
      - postgres_dumps:/dumps
    environment:
      - TZ=${TZ}
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=atuin,npm
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_ON_START=TRUE
      - BACKUP_DIR=/dumps
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - diun.enable=true

  adminer:
    image: docker.io/adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8083:8080
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - diun.enable=true

volumes:
  postgres_data:
  postgres_dumps:
