services:
  beszel-agent:
    image: docker.io/henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: always
    network_mode: host
    volumes:
      - beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LISTEN=/beszel_socket/beszel.sock
      - KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINlh9LAAR9jXqvrkeP1dpOvQPbrcAzQVcyK90s97MaxR
    labels:
      - diun.enable=true

  beszel:
    image: docker.io/henrygd/beszel:latest
    container_name: beszel
    restart: always
    ports:
      - 8090:8090
    volumes:
      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket
    environment:
      - APP_URL=https://beszel.local.ohlongjohnson.tech
    depends_on:
      - beszel-agent
    labels:
      - diun.enable=true

volumes:
  beszel_data:
  beszel_socket:
