services:
  npm:
    image: docker.io/jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - npm_data:/data
      - letsencrypt:/etc/letsencrypt
    environment:
      - DB_POSTGRES_HOST=postgres
      - DB_POSTGRES_PORT=5432
      - DB_POSTGRES_USER=${POSTGRES_USER}
      - DB_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRES_NAME=npm
    depends_on:
      - postgres
    labels:
      - diun.enable=true
volumes:
  npm_data:
  letsencrypt:
