{
  homeModules.packages = { pkgs, ... }: {
    home.packages =
      (with pkgs; [
        android-tools
        cargo
        deluge
        docker-compose
        drawing
        exiftool
        ffmpeg
        ffmpegthumbnailer
        file-roller
        filezilla
        firefox
        gcolor3
        gdu
        glab
        grim
        handy
        hurl
        imagemagick
        jdk
        jqp
        just
        kubectl
        kubernetes-helm
        libqalculate
        lima
        localsend
        nix-prefetch-github
        nodejs
        opentofu
        pandoc
        parallel
        pass
        pavucontrol
        phockup
        poppler
        proton-vpn
        rustc
        slurp
        tectonic
        tesseract
        thunar
        wl-clipboard
        worktrunk
        xre
        zotero
      ])
      ++ (with pkgs.local; [
        diff-persist
        gcp
        noctalia-settings-diff
      ]);
  };
}
