{
  homeModules.packages = { pkgs, ... }: {
    home.packages =
      (with pkgs; [
        android-tools
        bws
        deluge
        docker-compose
        drawing
        exiftool
        ffmpeg
        ffmpegthumbnailer
        file-roller
        filezilla
        firefox
        gcolor3
        gdu
        grim
        imagemagick
        jdk
        jqp
        just
        libqalculate
        libreoffice
        lima
        localsend
        nix-prefetch-github
        opentofu
        pandoc
        parallel
        pass
        pavucontrol
        phockup
        poppler
        proton-vpn
        slurp
        tectonic
        tesseract
        thunar
        wl-clipboard
        xre
        zotero
      ])
      ++ (with pkgs.local; [
        diff-persist
        noctalia-settings-diff
      ]);
  };
}
